spring.application.name=trueyield
# Verbindung zur MongoDB via Umgebungsvariable
spring.mongodb.uri=${MONGODB_URI}

# Optional: Zeige MongoDB Queries in der Konsole (hilfreich für Debugging)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Auth0 JWT Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/